PREPROCESSING:
  # DATASET: Celeb-DFv2
  # DATASET: DFW
  DATASET: FaceForensics
  COMPRESSION: c0
  SPLIT: train
  # SPLIT: val
  # SPLIT: test
  # ROOT: /mnt/g/내 드라이브/LAA-Net/data/deepfake_cluster/datasets_df/Celeb-DFv2/c0/
  # ROOT: /content/drive/MyDrive/LAA-Net/data/deepfake_cluster/datasets_df/FaceForensics++/c0/
  ROOT: /mnt/g/내 드라이브/LAA-Net/data/deepfake_cluster/datasets_df/FaceForensics++/c0/
  # ROOT: /mnt/g/내 드라이브/LAA-Net/data/deepfake_cluster/datasets_df/DFW/
  # ROOT: /content/drive/MyDrive/LAA-Net/data/deepfake_cluster/datasets_df/FaceForensics++/c0/
  # FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
  # FAKETYPE: [YouTube-real]
  FAKETYPE: [Original]
  # FAKETYPE: [real_test, fake_test]
  # FAKETYPE: [Celeb-real, Celeb-synthesis, YouTube-real]
  IMAGE_SUFFIX: png
  DATA_TYPE: frames
  LABEL: [real]
  facial_lm_pretrained: pretrained/shape_predictor_81_face_landmarks.dat
  # facial_lm_pretrained: pretrained/shape_predictor_68_face_landmarks.dat
  N_LANDMARKS: 81
  # N_LANDMARKS: 68
  SAMPLING:
    ACTIVE: False
    NUMBERS: 8
  DEBUG: False
